on: [ push ]
name: Run Python Tests
jobs:
  pytest:
    strategy:
      matrix:
        version: [14,15]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: build instrumenter
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main'
          sudo apt remove clang-14 clang-13 clang-12 llvm-14 llvm-13 llvm-12
          sudo apt-get update
          sudo apt-get install ninja-build catch2 clang-${{ matrix.version }} libclang-${{ matrix.version }}-dev libclang-cpp${{ matrix.version }}-dev
          python -m pip install build
          ./build_python_wheel_local.sh
      - run: python -m pip install . pytest
      - name: run pytest
        run: python -m pytest python_src/test
